version: '3.8'

services:
  app:
    build: .
    container_name: notejam_django
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: notejam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: "yFdFYoN/TNCFJeyNRgRkIgBIjUspIV+nU4kiD+yZlNg="
      DEBUG: "True"

  db:
    image: postgres
    container_name: notejam_db
    restart: always
    environment:
      POSTGRES_DB: notejam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
