apiVersion: v1
kind: Service
metadata:
  name: notejam-app-service
  namespace: notejam
spec:
  selector:
    app: notejam-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30000
  # type: ClusterIP
  type: NodePort
