apiVersion: v1
kind: Service
metadata:
  name: notejam-db-statefulset
  namespace: notejam
spec:
  selector:
    app: notejam-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notejam-db-statefulset
  namespace: notejam
spec:
  serviceName: "notejam-db-statefulset"
  replicas: 1
  selector:
    matchLabels:
      app: notejam-db
  template:
    metadata:
      labels:
        app: notejam-db
    spec:
      containers:
      - name: notejam-db
        image: swapxs/notejam-db
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: notejam-config
              key: db_user
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: notejam-config
              key: db_name
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notejam-secret
              key: db_password
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
