apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notejam-db-persistent-volume-claim
  namespace: notejam
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
