apiVersion: v1
kind: PersistentVolume
metadata:
  name: notejam-db-pv
  namespace: notejam
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/notejam-db
